---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

os: "linux"
dist: "xenial"
language: "python"

services:
- "docker"

install:
# Install dependencies
- "pip install ansible ansible-lint yamllint molecule docker"

# Make sure the role is found
- "cd .."
- "ln -s ansible-role-mosh mireiawen.mosh"

# Print versions before running
before_script:
- "ansible --version"
- "ansible-lint --version"
- "yamllint --version"
- "molecule --version"

stages:
- "test"

jobs:
  include:

  # Default test: Alpine
  - stage: "test"
    name: "Alpine"
    script:
    - "molecule test"
