---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

os: "linux"
dist: "xenial"
language: "python"

# Python versions to test on
python:
- "3.7"
- "3.8"

services:
- "docker"

install:
# Install dependencies
- "pip install ansible ansible-lint yamllint molecule docker"

# Add ansible.cfg to pick up roles path.
- "printf '[defaults]\nroles_path = ../' > ansible.cfg"

# Print versions before running
before_script:
- "cat ansible.cfg"
- "ansible --version"
- "ansible-lint --version"
- "yamllint --version"
- "molecule --version"

stages:
- "test"

jobs:
  include:
  
  # Default test: Alpine
  - stage: "test"
    name: "Alpine"
    script:
    - "molecule test"
