---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

os: "linux"
dist: "xenial"
language: "python"

# Python versions to test on
python:
- "2.7"
- "3.7"
- "3.8"

services:
- "docker"

install:
# Install dependencies
- "pip install ansible ansible-lint yamllint molecule docker"

# Add ansible.cfg to pick up roles path.
- "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
# Print versions
- "ansible --version"
- "ansible-lint --version"
- "yamllint --version"
- "molecule --version"

# Default test: Alpine
- "molecule test"

# Test: Arch Linux
- "molecule test --scenario-name arch"

# Test: CentOS
- "molecule test --scenario-name centos"

# Test: Debian
- "molecule test --scenario-name debian"

# Test: Fedora
- "molecule test --scenario-name fedora"

# Test: OpenSUSE
- "molecule test --scenario-name opensuse"

# Test: Ubuntu
- "molecule test --scenario-name ubuntu"
