---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

- name: 'Install Mobile Shell (MoSH)'
  ansible.builtin.package:
    name: '{{ mosh_package }}'
    state: '{{ mosh_state }}'
